### ISSUE TITLE
Club Logos Displayed along with the names in the chrome extension tray

### ISSUE THREAD

**Issue by humachine** [mingchia-andy-liu/chrome-extension-nba#1]
Club logos (unofficial/cartoon-like) would be great to have along with the club names.

**Comment by mingchia-andy-liu** [comment]
That's a good idea but I don't know all the legal side stuff. Maybe some time in the future I will investigate about it.

**Comment by humachine** [comment]
Not worth the hassle of putting in the original logos and worrying about legal troubles. But it would be easy to put in alternate hand-drawn logos. 

Do close this request, if you feel this can be done later.

**Comment by mingchia-andy-liu** [comment]
Yeah, will close this for now.

Reopen when I am on the task.
