### ISSUE TITLE
[Bug] Score not shown next to titles on the Left-side navigation bar

### ISSUE THREAD

**Issue by humachine** [mingchia-andy-liu/chrome-extension-nba#19]
Scores are seen here
![image](https://user-images.githubusercontent.com/5187366/34038480-56a18f26-e141-11e7-993c-1b8ae672b92a.png)

Even though the match is over (and the scores can be seen on the box score on the right), the score is not shown next to the game title.
![image](https://user-images.githubusercontent.com/5187366/34038499-67279d22-e141-11e7-8c47-a6badfef1221.png)

**Comment by mingchia-andy-liu** [comment]
addressed in 3ee06ab833ead451708d3bcb73abd174aa08e9cf

**Comment by mingchia-andy-liu** [comment]
Fixed in 1.2.5
