### ISSUE TITLE
No games shown on opening day. 

### ISSUE THREAD

**Issue by humachine** [mingchia-andy-liu/chrome-extension-nba#2]
![image](https://user-images.githubusercontent.com/5187366/31697570-3a157356-b36d-11e7-97be-382057ef5f12.png)

**Comment by mingchia-andy-liu** [comment]
The daily API has been unstable/not up to date with the actual score.
I will see if I can use the full schedule to display on the popup

**Comment by mingchia-andy-liu** [comment]
Fixed in #8
