### ISSUE TITLE
Final score of completed games not displayed on overview

### ISSUE THREAD

**Issue by keldian** [mingchia-andy-liu/chrome-extension-nba#664]
**Describe the bug**
Where the score should be displayed, instead it says `- 0 Qtr` or the game start time eg `@ 01:00 AM`  (on past games, possibly also ongoing ones).

**Environment**
 - OS: Windows 10
 - Browser: Firefox
 - Browser Version: 105.0.3
 - Extension Version: 1.5.1

**To Reproduce**
N/A

**Expected behavior**
Final score is displayed for all completed games.

**Screenshots**
![image](https://user-images.githubusercontent.com/953679/195908738-f807a98b-5351-47ce-a055-30769fdb4a08.png)

**Additional context**
Bug starts at day 2022-10-03. Going further back, scores are visible.

**Comment by Lokoko01** [comment]
Hi,
Any update about this bug ?
The scoreboard route doesn't seem to display linescores and other infos since the 3rd of october

Thks

**Comment by mingchia-andy-liu** [comment]
Hi @keldian @Lokoko01, sorry for the delay, looks like nba decommissioned the endpoint, I thought it was only for preseason games, looks like it's also for regular season games. 
I will find a new one and patch it this weekend.

**Comment by Lokoko01** [comment]
Hi @mingchia-andy-liu,
Thanks for the reply. 

Do you think it's definitive ?

**Comment by mingchia-andy-liu** [comment]
Hi @keldian @Lokoko01 , the issue should be fixed in 1.5.2 release. Chrome & Firefox are both just published. Let me know if you see anymore issue.

**Comment by Lokoko01** [comment]
Hi @mingchia-andy-liu,
Thanks for your fix !

So just for information, the endpoint from data.nba.net is down ? All endpoints from data.nba.net are down ?

**Comment by keldian** [comment]
Looks good. Thank you for your work on this extension.

**Comment by mingchia-andy-liu** [comment]
Hi @Lokoko01, looks like they don't update the old one anymore, I am using `data.nba.net/prod/v2/yyyyMMdd/scoreboard.json` requires `origin` and `referer` headers.

**Comment by Lokoko01** [comment]
Ok thank you @mingchia-andy-liu. That's weird to give up this endpoint... I don't understand why...
