### ISSUE TITLE
Standings not updating

### ISSUE THREAD

**Issue by keldian** [mingchia-andy-liu/chrome-extension-nba#804]
**Describe the bug**
New regular season one week in, standings are stuck on the previous season's.

**Environment**
 - KDE Neon
 - Firefox 119.0 
 - Extension Version 1.5.5

**Expected behavior**
Standing sheets up to date with real-time standings.

**Additional context**
Extension is working well otherwise as far as I've noticed.

**Comment by mingchia-andy-liu** [comment]
fixed in bb7a2dbe831a7d1ba58ffe31461f0aa396b94f24

**Comment by mingchia-andy-liu** [comment]
fixed in 1.5.6

**Comment by keldian** [comment]
Confirmed. Big thanks for continuing to maintain this awesome extension.
